# Generated by Django 3.2.9 on 2021-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try5app', '0002_alter_contacts_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pics')),
                ('heading', models.CharField(max_length=30)),
                ('descr', models.TextField()),
            ],
        ),
    ]
